#!/bin/bash
# Script para adicionar todas as colunas faltantes no BigQuery
# Baseado nos headers reais das abas do Google Sheets

PROJECT_ID="operaciones-br"
DATASET="sales_intelligence"

echo "🔧 Adicionando colunas faltantes no BigQuery..."

# ============================================
# PIPELINE (🎯 Análise Forecast IA)
# ============================================
echo "📊 Atualizando schema: pipeline"

bq query --project_id=$PROJECT_ID --use_legacy_sql=false "
ALTER TABLE \`${PROJECT_ID}.${DATASET}.pipeline\`
ADD COLUMN IF NOT EXISTS Run_ID STRING,
ADD COLUMN IF NOT EXISTS Oportunidade STRING,
ADD COLUMN IF NOT EXISTS Conta STRING,
ADD COLUMN IF NOT EXISTS Perfil STRING,
ADD COLUMN IF NOT EXISTS Produtos STRING,
ADD COLUMN IF NOT EXISTS Vendedor STRING,
ADD COLUMN IF NOT EXISTS Gross FLOAT64,
ADD COLUMN IF NOT EXISTS Net FLOAT64,
ADD COLUMN IF NOT EXISTS Fase_Atual STRING,
ADD COLUMN IF NOT EXISTS Forecast_SF STRING,
ADD COLUMN IF NOT EXISTS Fiscal_Q STRING,
ADD COLUMN IF NOT EXISTS Data_Prevista DATE,
ADD COLUMN IF NOT EXISTS Ciclo_dias INT64,
ADD COLUMN IF NOT EXISTS Dias_Funil INT64,
ADD COLUMN IF NOT EXISTS Atividades INT64,
ADD COLUMN IF NOT EXISTS Atividades_Peso FLOAT64,
ADD COLUMN IF NOT EXISTS Mix_Atividades STRING,
ADD COLUMN IF NOT EXISTS Idle_Dias INT64,
ADD COLUMN IF NOT EXISTS Qualidade_Engajamento STRING,
ADD COLUMN IF NOT EXISTS Forecast_IA STRING,
ADD COLUMN IF NOT EXISTS Confianca INT64,
ADD COLUMN IF NOT EXISTS Motivo_Confianca STRING,
ADD COLUMN IF NOT EXISTS MEDDIC_Score INT64,
ADD COLUMN IF NOT EXISTS MEDDIC_Gaps STRING,
ADD COLUMN IF NOT EXISTS MEDDIC_Evidencias STRING,
ADD COLUMN IF NOT EXISTS BANT_Score INT64,
ADD COLUMN IF NOT EXISTS BANT_Gaps STRING,
ADD COLUMN IF NOT EXISTS BANT_Evidencias STRING,
ADD COLUMN IF NOT EXISTS Justificativa_IA STRING,
ADD COLUMN IF NOT EXISTS Regras_Aplicadas STRING,
ADD COLUMN IF NOT EXISTS Incoerencia_Detectada STRING,
ADD COLUMN IF NOT EXISTS Perguntas_de_Auditoria_IA STRING,
ADD COLUMN IF NOT EXISTS Flags_de_Risco STRING,
ADD COLUMN IF NOT EXISTS Gaps_Identificados STRING,
ADD COLUMN IF NOT EXISTS Cod_Acao STRING,
ADD COLUMN IF NOT EXISTS Acao_Sugerida STRING,
ADD COLUMN IF NOT EXISTS Risco_Principal STRING,
ADD COLUMN IF NOT EXISTS Total_Mudancas INT64,
ADD COLUMN IF NOT EXISTS Mudancas_Criticas INT64,
ADD COLUMN IF NOT EXISTS Mudancas_Close_Date INT64,
ADD COLUMN IF NOT EXISTS Mudancas_Stage INT64,
ADD COLUMN IF NOT EXISTS Mudancas_Valor INT64,
ADD COLUMN IF NOT EXISTS Anomalias_Detectadas STRING,
ADD COLUMN IF NOT EXISTS Velocity_Predicao STRING,
ADD COLUMN IF NOT EXISTS Velocity_Detalhes STRING,
ADD COLUMN IF NOT EXISTS Territorio_Correto STRING,
ADD COLUMN IF NOT EXISTS Vendedor_Designado STRING,
ADD COLUMN IF NOT EXISTS Estado_Cidade_Detectado STRING,
ADD COLUMN IF NOT EXISTS Fonte_Deteccao STRING,
ADD COLUMN IF NOT EXISTS Calendario_Faturacao STRING,
ADD COLUMN IF NOT EXISTS Valor_Reconhecido_Q1 FLOAT64,
ADD COLUMN IF NOT EXISTS Valor_Reconhecido_Q2 FLOAT64,
ADD COLUMN IF NOT EXISTS Valor_Reconhecido_Q3 FLOAT64,
ADD COLUMN IF NOT EXISTS Valor_Reconhecido_Q4 FLOAT64,
ADD COLUMN IF NOT EXISTS Ultima_Atualizacao STRING,
ADD COLUMN IF NOT EXISTS data_carga TIMESTAMP
;"

# ============================================
# CLOSED_DEALS_WON (📈 Análise Ganhas)
# ============================================
echo "📊 Atualizando schema: closed_deals_won"

bq query --project_id=$PROJECT_ID --use_legacy_sql=false "
ALTER TABLE \`${PROJECT_ID}.${DATASET}.closed_deals_won\`
ADD COLUMN IF NOT EXISTS Run_ID STRING,
ADD COLUMN IF NOT EXISTS Oportunidade STRING,
ADD COLUMN IF NOT EXISTS Conta STRING,
ADD COLUMN IF NOT EXISTS Perfil_Cliente STRING,
ADD COLUMN IF NOT EXISTS Vendedor STRING,
ADD COLUMN IF NOT EXISTS Gross FLOAT64,
ADD COLUMN IF NOT EXISTS Net FLOAT64,
ADD COLUMN IF NOT EXISTS Portfolio STRING,
ADD COLUMN IF NOT EXISTS Segmento STRING,
ADD COLUMN IF NOT EXISTS Familia_Produto STRING,
ADD COLUMN IF NOT EXISTS Status STRING,
ADD COLUMN IF NOT EXISTS Fiscal_Q STRING,
ADD COLUMN IF NOT EXISTS Data_Fechamento DATE,
ADD COLUMN IF NOT EXISTS Ciclo_dias INT64,
ADD COLUMN IF NOT EXISTS Produtos STRING,
ADD COLUMN IF NOT EXISTS Resumo_Analise STRING,
ADD COLUMN IF NOT EXISTS Causa_Raiz STRING,
ADD COLUMN IF NOT EXISTS Fatores_Sucesso STRING,
ADD COLUMN IF NOT EXISTS Tipo_Resultado STRING,
ADD COLUMN IF NOT EXISTS Qualidade_Engajamento STRING,
ADD COLUMN IF NOT EXISTS Gestao_Oportunidade STRING,
ADD COLUMN IF NOT EXISTS Licoes_Aprendidas STRING,
ADD COLUMN IF NOT EXISTS Atividades INT64,
ADD COLUMN IF NOT EXISTS Ativ_7d INT64,
ADD COLUMN IF NOT EXISTS Ativ_30d INT64,
ADD COLUMN IF NOT EXISTS Distribuicao_Tipos STRING,
ADD COLUMN IF NOT EXISTS Periodo_Pico STRING,
ADD COLUMN IF NOT EXISTS Cadencia_Media_dias STRING,
ADD COLUMN IF NOT EXISTS Total_Mudancas INT64,
ADD COLUMN IF NOT EXISTS Mudancas_Criticas INT64,
ADD COLUMN IF NOT EXISTS Mudancas_Close_Date INT64,
ADD COLUMN IF NOT EXISTS Mudancas_Stage INT64,
ADD COLUMN IF NOT EXISTS Mudancas_Valor INT64,
ADD COLUMN IF NOT EXISTS Campos_Alterados STRING,
ADD COLUMN IF NOT EXISTS Padrao_Mudancas STRING,
ADD COLUMN IF NOT EXISTS Freq_Mudancas STRING,
ADD COLUMN IF NOT EXISTS Editores INT64,
ADD COLUMN IF NOT EXISTS Labels STRING,
ADD COLUMN IF NOT EXISTS Ultima_Atualizacao STRING,
ADD COLUMN IF NOT EXISTS outcome STRING,
ADD COLUMN IF NOT EXISTS data_carga TIMESTAMP
;"

# ============================================
# CLOSED_DEALS_LOST (📉 Análise Perdidas)
# ============================================
echo "📊 Atualizando schema: closed_deals_lost"

bq query --project_id=$PROJECT_ID --use_legacy_sql=false "
ALTER TABLE \`${PROJECT_ID}.${DATASET}.closed_deals_lost\`
ADD COLUMN IF NOT EXISTS Run_ID STRING,
ADD COLUMN IF NOT EXISTS Oportunidade STRING,
ADD COLUMN IF NOT EXISTS Conta STRING,
ADD COLUMN IF NOT EXISTS Perfil_Cliente STRING,
ADD COLUMN IF NOT EXISTS Vendedor STRING,
ADD COLUMN IF NOT EXISTS Gross FLOAT64,
ADD COLUMN IF NOT EXISTS Net FLOAT64,
ADD COLUMN IF NOT EXISTS Portfolio STRING,
ADD COLUMN IF NOT EXISTS Segmento STRING,
ADD COLUMN IF NOT EXISTS Familia_Produto STRING,
ADD COLUMN IF NOT EXISTS Status STRING,
ADD COLUMN IF NOT EXISTS Fiscal_Q STRING,
ADD COLUMN IF NOT EXISTS Data_Fechamento DATE,
ADD COLUMN IF NOT EXISTS Ciclo_dias INT64,
ADD COLUMN IF NOT EXISTS Produtos STRING,
ADD COLUMN IF NOT EXISTS Resumo_Analise STRING,
ADD COLUMN IF NOT EXISTS Causa_Raiz STRING,
ADD COLUMN IF NOT EXISTS Causas_Secundarias STRING,
ADD COLUMN IF NOT EXISTS Tipo_Resultado STRING,
ADD COLUMN IF NOT EXISTS Evitavel STRING,
ADD COLUMN IF NOT EXISTS Sinais_Alerta STRING,
ADD COLUMN IF NOT EXISTS Momento_Critico STRING,
ADD COLUMN IF NOT EXISTS Licoes_Aprendidas STRING,
ADD COLUMN IF NOT EXISTS Atividades INT64,
ADD COLUMN IF NOT EXISTS Ativ_7d INT64,
ADD COLUMN IF NOT EXISTS Ativ_30d INT64,
ADD COLUMN IF NOT EXISTS Distribuicao_Tipos STRING,
ADD COLUMN IF NOT EXISTS Periodo_Pico STRING,
ADD COLUMN IF NOT EXISTS Cadencia_Media_dias STRING,
ADD COLUMN IF NOT EXISTS Total_Mudancas INT64,
ADD COLUMN IF NOT EXISTS Mudancas_Criticas INT64,
ADD COLUMN IF NOT EXISTS Mudancas_Close_Date INT64,
ADD COLUMN IF NOT EXISTS Mudancas_Stage INT64,
ADD COLUMN IF NOT EXISTS Mudancas_Valor INT64,
ADD COLUMN IF NOT EXISTS Campos_Alterados STRING,
ADD COLUMN IF NOT EXISTS Padrao_Mudancas STRING,
ADD COLUMN IF NOT EXISTS Freq_Mudancas STRING,
ADD COLUMN IF NOT EXISTS Editores INT64,
ADD COLUMN IF NOT EXISTS Labels STRING,
ADD COLUMN IF NOT EXISTS Ultima_Atualizacao STRING,
ADD COLUMN IF NOT EXISTS outcome STRING,
ADD COLUMN IF NOT EXISTS data_carga TIMESTAMP
;"

# ============================================
# SALES_SPECIALIST
# ============================================
echo "📊 Atualizando schema: sales_specialist"

bq query --project_id=$PROJECT_ID --use_legacy_sql=false "
ALTER TABLE \`${PROJECT_ID}.${DATASET}.sales_specialist\`
ADD COLUMN IF NOT EXISTS Account_Name STRING,
ADD COLUMN IF NOT EXISTS Perfil STRING,
ADD COLUMN IF NOT EXISTS Opportunity_Name STRING,
ADD COLUMN IF NOT EXISTS Meses_Fat STRING,
ADD COLUMN IF NOT EXISTS GTM_2026 STRING,
ADD COLUMN IF NOT EXISTS Booking_Total_Gross FLOAT64,
ADD COLUMN IF NOT EXISTS Booking_Total_Net FLOAT64,
ADD COLUMN IF NOT EXISTS Status STRING,
ADD COLUMN IF NOT EXISTS Vendedor STRING,
ADD COLUMN IF NOT EXISTS Status_1 STRING,
ADD COLUMN IF NOT EXISTS Billing_Quarter FLOAT64,
ADD COLUMN IF NOT EXISTS Billing_Quarter_1 FLOAT64,
ADD COLUMN IF NOT EXISTS Closed_Date DATE,
ADD COLUMN IF NOT EXISTS data_carga TIMESTAMP
;"

echo "✅ Schemas atualizados com sucesso!"
echo ""
echo "📋 Para verificar as colunas adicionadas:"
echo "bq show --schema --format=prettyjson ${PROJECT_ID}:${DATASET}.pipeline | jq -r '.[].name' | wc -l"
