steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/operaciones-br/sales-intelligence-engine-run', '-f', 'cloud-run/Dockerfile', '.']
images:
  - 'gcr.io/operaciones-br/sales-intelligence-engine-run'
